# Generated by Django 3.2.6 on 2023-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countApp1', '0002_auto_20230926_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addall',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
