# Generated by Django 3.2.6 on 2023-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countApp1', '0003_alter_addall_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addall',
            name='Date',
            field=models.DateField(),
        ),
    ]
